# Generated by Django 3.1 on 2021-05-29 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_auto_20210529_1700'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category_slug',
            new_name='slug',
        ),
    ]
